# Generated by Django 5.2.8 on 2025-11-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymodel_core_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='accessories_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
