# Generated by Django 5.2.8 on 2025-11-27 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorymodel_accessories_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineVariantModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_name', models.CharField(default='', max_length=255)),
                ('core_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overhaul_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('top_overhaul_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('accessories_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventorymodel',
            name='accessories_cost',
        ),
        migrations.RemoveField(
            model_name='inventorymodel',
            name='core_cost',
        ),
        migrations.RemoveField(
            model_name='inventorymodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventorymodel',
            name='overhaul_cost',
        ),
        migrations.RemoveField(
            model_name='inventorymodel',
            name='top_overhaul_cost',
        ),
        migrations.AddField(
            model_name='inventorymodel',
            name='project_name',
            field=models.CharField(default='RAE???', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='serial_number',
            field=models.CharField(default='NOT GIVEN', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorymodel',
            name='engine_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.enginevariantmodel'),
        ),
    ]
