# Generated by Django 5.2.8 on 2025-11-27 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_enginevariantmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='engine_variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='inventory.enginevariantmodel'),
        ),
    ]
