# Generated by Django 5.2.8 on 2025-11-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorymodel_engine_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='estimated_availability',
            field=models.DateField(default=None, null=True),
        ),
    ]
