# Generated by Django 5.2.8 on 2025-11-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorymodel_estimated_availability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryModel',
            new_name='EngineInventoryModel',
        ),
    ]
